pluginManagement {
    repositories {
        maven {
            name = 'NeoForged'
            url 'https://maven.neoforged.net/releases'
        }
        maven {
            name = 'GeckoLib'
            url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
        }
        maven {
            name = 'Modrinth'
            url 'https://api.modrinth.com/maven'
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'CatoxidesBattleRebuild'